name: Desktop Release Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build Artifacts
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        include:
          - os: ubuntu-latest
            artifact_glob: '**/*.deb'  # 修改通配符格式
          - os: windows-latest
            artifact_glob: '**/*.msi,**/*.exe'
          - os: macos-latest
            artifact_glob: '**/*.dmg'

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Grant execute permission for gradlew
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Build with Gradle
        shell: bash
        run: |
          # 统一处理不同操作系统的换行符
          git config --global core.autocrlf input
          ./gradlew :composeApp:packageReleaseDistributionForCurrentOS \
            --warning-mode all \
            --no-daemon \
            --console=plain \
            -Dorg.gradle.jvmargs='-Xmx4g' \
            -Dorg.gradle.daemon=false
        env:
          TERM: dumb  # 禁用交互式功能
          CI: true    # 启用CI模式（部分插件会根据此变量调整行为）

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-binaries
          path: |
            composeApp/build/compose/binaries/main-release/${{ matrix.artifact_glob }}
          if-no-files-found: error

  release:
    name: Create Release
    needs: build  # 等待所有构建作业完成
    runs-on: ubuntu-latest
    steps:
      - name: Get Version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: combined-artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          files: |
            combined-artifacts/**/*